# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main
stages:
- stage: 'build'

variables: 
   buildConfiguration: 'release'
   
  jobs:
  - job: 'buildjob'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: restore
          projects: '**/*.csproj'

      - task: DotNetCoreCLI@2
        inputs:
          command: build
          projects: '**/*.csproj'
          configuration: '$(build.configuration)'


